version: '3.8'
services:
  cache:
    image: redis/redis-stack:7.2.0-v9
    restart: always
    ports:
      - '8001:8001'
    environment:
      - REDIS_ARGS="--requirepass mypassword"
    volumes: 
      - cache:/data
  external-api:
    image: codeberg.org/birkenfunk/sqs-external-api:latest
    restart: always
  api:
    image: codeberg.org/birkenfunk/sqs/backend:0.1.1
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - WEATHER_SERVICE_API_URL=http://external-api:3000
      - REDIS_URL=cache:6379
volumes:
  cache:
    driver: local
