name: build

on:
    push

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.0
            - name: Get dependencies
              run: flutter pub get
              working-directory: ./src
            - name: Test
              run: make test
              working-directory: ./src
    integationTests:
        runs-on: ubuntu-22.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.0
            - name: install Buildkit
              run: |
                sudo apt-get update -y
                sudo apt-get install -y ninja-build libgtk-3-dev
            - name: Get dependencies
              run: flutter pub get
              working-directory: ./src
            - name: Test
              run: |
                export DISPLAY=:99
                sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
                make integration_test_linux
              working-directory: ./src
    buildLinux:
        runs-on: ubuntu-22.04
        needs: 
            - integationTests
            - test
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.0
            - run: |
                sudo apt-get update -y
                sudo apt-get install -y ninja-build libgtk-3-dev
            
            - name: Get dependencies
              run: flutter pub get
              working-directory: ./src
            - name: Build
              run: make build_linux
              working-directory: ./src
            - name: Upload linux build
              uses: actions/upload-artifact@v4
              with:
                name: linuxBuild
                path: src/build/linux/x64/release/bundle
    buildWeb:
        runs-on: ubuntu-22.04
        needs: 
            - integationTests
            - test
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.0
            - name: Get dependencies
              run: flutter pub get
              working-directory: ./src
            - name: Build
              run: make build_web
              working-directory: ./src
            - name: Upload web build
              uses: actions/upload-artifact@v4
              with:
                name: webBuild
                path: src/build/web
    buildAdriod:
        runs-on: ubuntu-22.04
        needs: 
            - integationTests
            - test
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.0
            - name: Get dependencies
              run: flutter pub get
              working-directory: ./src
            - name: Build
              run: make build_android
              working-directory: ./src
            - name: Upload adroid build
              uses: actions/upload-artifact@v4
              with:
                name: androidBuild
                path: src/build/app/outputs/flutter-apk/app-release.apk
    publish:
      runs-on: ubuntu-22.04
      needs: 
        - buildAdriod
        - buildLinux
        - buildWeb
      steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Download Builds
          uses: actions/download-artifact@v4
        - run: ls -la